### ISSUE TITLE
Feature request: Max duration

### ISSUE THREAD

**Issue by rensieeee** [sanctuuary/APE#40]
Could it be possible to create an optional "max duration" parameter to APE? This way, when the user runs APE with ontologies and data that takes a lot of time, the user can limit the amount of time APE can take to find any workflows. It also protects the user's system from crashing, due to APE taking up too much memory in calculating workflows.

**Comment by vedran-kasalica** [comment]
APE 1.1.3 introduced a configuration field "timeout(sec)"
