### ISSUE TITLE
Ambiguity issues when running APE with incomplete data parameters

### ISSUE THREAD

**Issue by rensieeee** [sanctuuary/APE#44]
When creating a constrains.json file to run a query for ImageMagick, the following json structure is currently expected:

`
  "constraints": [
    {​​​​
      "constraintid": "use_ite_t",
      "parameters": [
        {​​​​ "Type" : ["Filter"]}​​​​,
        {​​​​ "Format": ["JPG"]}​​​​
      ]
    }​​​​,
    {​​​​
      "constraintid": "use_t",
      "parameters": [
        {​​​​ "Type" : ["Filter"]}​​​​
      ]
    }​​​​
  ]
}​​​​
`

This creates an ambiguity problem when interpreting these parameters, specifically for the use_ite_t constraint. This constraint accepts 2 inputs, but it's not clear which taxonomy refers to which input. It could be that both taxonomies refer to parameter 1, or both to parameter 2, or even 1 for parameter 1 and 1 for parameter 2.

Now, I'm not sure if use_ite_t accepts an input to be completely empty, if not, you could determine these parameters need to occupy 2 inputs and thus conclude that each parameter applies to only 1 input, partially filling both inputs. However, this logic becomes unusable when using a domain with 3 or more taxonomies per input. Then it becomes impossible to accurately couple a parameter to the correct data type.

I think there are 2 possible solutions: The first one is to disable the option to fill in data types partially. Require all taxonomies to be filled. You can still use the taxonomy root for the same effect.

The other option is to rework the way config is read to allow for this format:
`
{​​​​
      "constraintid": "use_ite_t",
      "parameters": [
        {​​​​ "Type" : ["Filter"], "Format": ["JPG"]}​​​​,
        {​​​​ "Format": ["JPG"]}​​​​
      ]
}​​​​
`

This way, its clear that the second parameter contains an empty taxonomy, without having the ambiguity. Each data type parameter can have its own object, with all specified taxonomies as properties. I think this is the better method of the two.

Furthermore, as a nice to have: To change the parameter "constraintid" to "constraint_id", and move the value of the taxonomy out of the array. These changes make the json in general nicer to view and work with.

**Comment by vedran-kasalica** [comment]
The example you have given is not exactly how the constraint structure is expected. Although your example might be parsed, the format expected covers each data dimension for each parameter, as follows:

    {"constraints": [ 
    {​​​​ "constraintid": "use_ite_t", "parameters": [ {​​​​ "Type" : ["Filter"],  "Format" : ["PNG"]}​​​​, {​​​​  "Type" : ["Filter"], "Format": ["JPG"]}​​​​ ] }​​​​,
	{​​​​ "constraintid": "use_t", "parameters": [ {​​​​ "Type" : ["Filter"], "Format" : ["PNG"]}​​​​ ] }​​​​ 
    ] }

An example can be seen https://github.com/sanctuuary/APE_UseCases/blob/master/QuAnGIS/No1/constraints10.json

If a parameter is supposed to be an operation, only one dimension is given (as operations have one dimensional taxonomy), while for data parameters each dimension has to be described for each parameter.

Regarding the comment about the taxonomy value being an array, it's given for a reason, as a person can specify "Format": ["JPG", "PNG"] interpreted as a format should be "JPG" or "PNG".

Hope this answers your questions.

**Comment by rensieeee** [comment]
Okay, so I interpreted the inputs wrong. Does that mean this constraints file is invalid? https://github.com/sanctuuary/APE_UseCases/blob/master/ImageMagick/Example2/constraints.json.

This file includes a type constraint without explicit mentioning of all dimensions. This does work, but it is not the expected input?

Thanks for clarifying the arrays, I didn't know that was a feature.

**Comment by vedran-kasalica** [comment]
Thank you for point that constraint out, I have fixed the syntax.

Supporting arrays is a feature that is not crucial for the work of the library, but allows more flexibility for advanced users.

**Comment by rensieeee** [comment]
Alright, thanks for the clarification. Then I believe this issue can be resolved.
